---
- name: Copy Prometheus Config File
  ansible.builtin.copy:
    src: prometheus/prometheus.yml.j2
    dest: "/path/on/host/prometheus/prometheus.yml"
    mode: "0644"

- name: Copy Node Exporter Service File
  ansible.builtin.copy:
    src: systemd/node_exporter.service
    dest: "/path/on/host/systemd/node_exporter.service"
    mode: "0644"

- name: Copy CAdvisor Service File
  ansible.builtin.copy:
    src: systemd/cadvisor.service
    dest: "/path/on/host/systemd/cadvisor.service"
    mode: "0644"

- name: Deploy Docker Stack
  community.general.docker_compose:
    project_src: "{{ playbook_dir }}/roles/docker_stack"
    project_name: my_docker_stack
    definition: docker-compose.yml
    state: present
