---
- name: Pull Prometheus Docker Image
  community.docker.docker_image:
    name: prom/prometheus
    tag: "{{ prometheus_version }}"
    source: pull

- name: Run Prometheus Container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:{{ prometheus_version }}
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - "{{ prometheus_config_dest }}:/etc/prometheus/prometheus.yml:ro"

- name: Template Prometheus Config File
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dest }}"