---
- name: Template Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dest }}"
    owner: prometheus
    group: prometheus
  vars:
    # Add variables needed for the Prometheus configuration

- name: Deploy Docker Compose stack for monitoring
  community.general.docker_compose:
    project_name: "{{ docker_compose_project_name }}"  # Define project name (optional)
    definition: docker-compose.yml.j2
    state: present
