---
prometheus_version: "2.30.0"
docker_compose_project_name: "monitoring"  # Optional, define project name
monitoring_network_name: "monitoring"  # Optional, define network name
# Define other variables as needed (e.g., network name)
